version: "3.8"

services:
  database:
    image: postgres:alpine3.18
    container_name: db_app
    ports:
      - "8889:5432"
    env_file:
      - .env
    volumes:
      - ./sql/extension.sql:/docker-entrypoint-initdb.d/extension.sql
      - ./postgres_dumb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8008:80"
    depends_on:
      - database

